### ISSUE TITLE
ba filter 

### ISSUE THREAD

**Issue by yishuwei** [meegpipe/meegpipe#19]
+filter/@ba/filter.m, line 35
x(i, end-delay+1:end) = fliplr(x(i, end-2*delay+1:end-delay));

Not sure why you make the last part of the filtered signal a mirrored copy of the signal just before it.
This causes some problem. For example, when I used it for filtering ECG, it produced false QRS peaks accordingly.

**Comment by germangh** [comment]
To correct for the delay of the filter I shift the filtered signal by an amount `delay` to the left. This means that I need to fill in `delay` samples at the end. I decided to use a mirrorred copy of the last signal samples to fill in those missing data points. The obvious alternative is to fill those with zeroes but that can introduce large discontinuities in the filtered signal. 

It is true that filling-in with a mirrored data copy can produce false QRS peaks. But isn't this really negligible? Typically, the delay of the filter should be much much shorter than the duration of the signal so this should be a very minor issue. If you think filling-in with zeroes would be better then I could add an extra parameter that allows the user to define the fill-in approach that the filter will use.

**Comment by yishuwei** [comment]
MATLAB's filtfilt looks good to me at correcting delay. In meegpipe's filters, filtfilt is used only for IIR filtering. Is there a reason not useing it for FIR too?

**Comment by yishuwei** [comment]
I also found that MATLAB's `filter` function can return an extra argument which is called the "final condition"
http://www.mathworks.com/help/matlab/ref/filter.html

When I checked it with FIR filters, I saw this "final condition" is of length 2*delay and the first half contains the filtered signal of the last part. Do you think it is a good idea to just use for correcting delay?

**Comment by germangh** [comment]
I don't use `filtfilt` with FIR filters because `filtfilt` can introduce artifacts in certain scenarios (e.g. when there are sudden sharp variations in the input signal), and correcting for the filter delay is trivial for FIR filters: you just need to shift the output of the filter according to the length of the FIR filter. Conclusion: it's not worth risking filtering artifacts to just correct for the lag introduced by FIR filter. On the other hand, IIR filters don't have a linear phase response meaning that they introduce phase distortions that cannot be corrected by simply shifting the output by certain lag. Thus to prevent phase distortions with IIR filter I have no choice but using `filtfilt`.
